---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy 
  labels:
    app: flask
    env: lab 

spec:
  selector:
    matchLabels:
      app: flask 
  replicas: 2  
  template:
    metadata:
      name: flask-pod 
      labels:
        app: flask
        env: lab
        tier: frontend 
        version: v1_AC
    spec:
      containers:
        - name: flask-pod-cont
          image: princecharu/flask-application:55
          ports:
            - containerPort: 8082