---
apiVersion: v1
kind: Service
metadata:
   name: flask-lb-svc
   labels:
     app: flask 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8082 
      protocol: TCP

  selector:
        app: flask
        
      